# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Junteng Liu"
title_separator          : "-"
name                     : &name "Junteng Liu"
description              : &description "Junteng Liu's academic portfolio"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://apd-toolathon.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "/LJT-Homepage" # the subpath of your site, e.g. "/blog"
repository               : "apd-toolathon/LJT-Homepage"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Junteng Liu"
  pronouns         : 
  bio              : "First-year PhD candidate at HKUST NLP Group. Research focuses on natural language processing and machine learning."
  location         : "Hong Kong"
  employer         : "Hong Kong University of Science and Technology"
  uri              : 
  email            : "jliugi@connect.ust.hk" 

  # Academic websites
  academia         : 
  arxiv            : 
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  inspire-hep      : 
  impactstory      : 
  orcid            : 
  semantic         : 
  ssrn             : 
  pubmed           : 
  researchgate     : 
  scopus           : 
  zotero           : 


  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "Vicent0205"
  kaggle           : 
  stackoverflow    : 

  # Social media
  artstation       : 
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : 
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : "junteng88716710"
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/ for social media previews
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
oauth:
  access_token:
    token                : # Use OAuth bearer token authentication to enable Staticman's private endpoints
  webhook_secret:         # Same secret used in staticman.yml configuration on the server side
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : 
feed:
  collections:
    - publications
    - talks
    - posts
  item:
    text: "Recent Posts"
    limit: 5
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-toc

# Build settings
markdown               : kramdown
highlighter            : rouge
lsi                    :
excerpt_separator      : "\n\n"
incremental            :

# Exclude from processing.
exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.md"
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
  - Dockerfile
  - .gitignore
  - .devcontainer
  - .github
  - node_modules
  - package.json
  - yarn.lock
  - .sass-cache
  - .jekyll-cache
  - _site
  - public
  - tmp
  - bin
  - log
  - docs
  - test
  - script
  - tools
