# Jekyll configuration
locale: en-US
site_theme: default
title: Junteng Liu
title_separator: "-"
name: &name Junteng Liu
description: &description Junteng Liu's academic portfolio
url: https://apd-toolathon.github.io/LJT-Homepage
baseurl: /LJT-Homepage
repository: apd-toolathon/LJT-Homepage
author:
  avatar: profile.png
  name: Junteng Liu
  pronouns:
  bio: First-year PhD candidate at HKUST NLP Group
  location:
  employer: Hong Kong University of Science and Technology
  uri:
  email: jliugi@connect.ust.hk
  academia:
  arxiv:
  googlescholar: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
  inspire-hep:
  impactstory:
  orcid:
  semantic:
  ssrn:
  pubmed:
  researchgate:
  scopus:
  zotero:
  bitbucket:
  codepen:
  dribbble:
  github: Vicent0205
  kaggle:
  stackoverflow:
  artstation:
  bluesky:
  facebook:
  flickr:
  foursquare:
  goodreads:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin:
  mastodon:
  medium:
  pinterest:
  soundcloud:
  telegram:
  tumblr:
  twitter: junteng88716710
  vine:
  weibo:
  wikipedia:
  xing:
  youtube:
  zhihu:
publication_category:
  books:
    title: Books
  manuscripts:
    title: Journal Articles
  conferences:
    title: Conference Papers
collections:
  pages:
    output: true
    permalink: /:basename/
  talks:
    output: true
    permalink: /talks/:year/:month/:day/:title/
  portfolio:
    output: true
    permalink: /portfolio/:year/:month/:day/:title/
  publications:
    output: true
    permalink: /publications/:year/:month/:day/:title/
